// Matriz original: 119 señales estratégicas.
window.RITUAL_SIGNALS = [
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Yoga",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Pilates",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Fitness y bienestar",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Gimnasio",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Nutrición",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Alimentación saludable",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Cuidado personal",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Belleza y skincare",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Meditación",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Vida saludable",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Compras online",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "Meta / Instagram",
    "territory": "Wellness y lifestyle",
    "interest": "Creadoras de bienestar",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "TikTok",
    "territory": "Wellness y lifestyle",
    "interest": "Fitness y deporte",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "TikTok",
    "territory": "Wellness y lifestyle",
    "interest": "Belleza y cuidado personal",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "TikTok",
    "territory": "Wellness y lifestyle",
    "interest": "Lifestyle y rutinas",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "TikTok",
    "territory": "Wellness y lifestyle",
    "interest": "Comida saludable",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "TikTok",
    "territory": "Wellness y lifestyle",
    "interest": "Contenido de autocuidado",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "TikTok",
    "territory": "Wellness y lifestyle",
    "interest": "Creadores de Pilates",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "TikTok",
    "territory": "Wellness y lifestyle",
    "interest": "Videos de rutinas matutinas",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "TikTok",
    "territory": "Wellness y lifestyle",
    "interest": "Videos de rutinas nocturnas",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "TikTok",
    "territory": "Wellness y lifestyle",
    "interest": "Contenido educativo de bienestar",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "TikTok",
    "territory": "Wellness y lifestyle",
    "interest": "Reseñas de productos",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "TikTok",
    "territory": "Wellness y lifestyle",
    "interest": "UGC wellness",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "YouTube / Google",
    "territory": "Wellness y lifestyle",
    "interest": "Rutina de autocuidado",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "YouTube / Google",
    "territory": "Wellness y lifestyle",
    "interest": "Pilates en casa",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "YouTube / Google",
    "territory": "Wellness y lifestyle",
    "interest": "Yoga para principiantes",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "YouTube / Google",
    "territory": "Wellness y lifestyle",
    "interest": "Cómo hidratarse",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "YouTube / Google",
    "territory": "Wellness y lifestyle",
    "interest": "Electrolitos",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "YouTube / Google",
    "territory": "Wellness y lifestyle",
    "interest": "Hábitos saludables",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "YouTube / Google",
    "territory": "Wellness y lifestyle",
    "interest": "Rutina antes de dormir",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "YouTube / Google",
    "territory": "Wellness y lifestyle",
    "interest": "Reseñas de suplementos",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "YouTube / Google",
    "territory": "Wellness y lifestyle",
    "interest": "Bebidas sin azúcar",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "YouTube / Google",
    "territory": "Wellness y lifestyle",
    "interest": "Nutrición diaria",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Valeria",
    "platform": "YouTube / Google",
    "territory": "Wellness y lifestyle",
    "interest": "Mindfulness",
    "type": "Interés si existe / señal contextual",
    "priority": "Alta",
    "product": "Día + Noche",
    "tactic": "Reach con creatividad y pruebas de afinidad",
    "validation": "Verificar etiqueta exacta en Ads Manager; no prometer segmentación literal"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Gimnasio",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Running",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Ciclismo",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Entrenamiento funcional",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "CrossFit",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Nutrición deportiva",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Proteínas",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Suplementos nutricionales",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Wearables",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Senderismo",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Fitness",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Productividad",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Deporte recreativo",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Instagram",
    "territory": "Vida activa y rendimiento",
    "interest": "Compras online",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Facebook",
    "territory": "Vida activa y rendimiento",
    "interest": "Ciclismo",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Facebook",
    "territory": "Vida activa y rendimiento",
    "interest": "Running",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Facebook",
    "territory": "Vida activa y rendimiento",
    "interest": "Gimnasio",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Facebook",
    "territory": "Vida activa y rendimiento",
    "interest": "Fitness",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Facebook",
    "territory": "Vida activa y rendimiento",
    "interest": "Nutrición deportiva",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Facebook",
    "territory": "Vida activa y rendimiento",
    "interest": "Tecnología",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Facebook",
    "territory": "Vida activa y rendimiento",
    "interest": "Deportes al aire libre",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "Meta / Facebook",
    "territory": "Vida activa y rendimiento",
    "interest": "Vida saludable",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "TikTok",
    "territory": "Vida activa y rendimiento",
    "interest": "Deportes y outdoor",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "TikTok",
    "territory": "Vida activa y rendimiento",
    "interest": "Fitness",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "TikTok",
    "territory": "Vida activa y rendimiento",
    "interest": "Videos de gimnasio",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "TikTok",
    "territory": "Vida activa y rendimiento",
    "interest": "Videos de running",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "TikTok",
    "territory": "Vida activa y rendimiento",
    "interest": "Tecnología wearable",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "TikTok",
    "territory": "Vida activa y rendimiento",
    "interest": "Nutrición deportiva",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "TikTok",
    "territory": "Vida activa y rendimiento",
    "interest": "Creadores de entrenamiento",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "TikTok",
    "territory": "Vida activa y rendimiento",
    "interest": "Rutinas de recuperación",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "TikTok",
    "territory": "Vida activa y rendimiento",
    "interest": "Contenido de hidratación",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "TikTok",
    "territory": "Vida activa y rendimiento",
    "interest": "Reseñas de suplementos",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "YouTube / Google",
    "territory": "Vida activa y rendimiento",
    "interest": "Cómo hidratarse al entrenar",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "YouTube / Google",
    "territory": "Vida activa y rendimiento",
    "interest": "Electrolitos para deporte",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "YouTube / Google",
    "territory": "Vida activa y rendimiento",
    "interest": "Rutina de gimnasio",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "YouTube / Google",
    "territory": "Vida activa y rendimiento",
    "interest": "Recuperación después de correr",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "YouTube / Google",
    "territory": "Vida activa y rendimiento",
    "interest": "Nutrición deportiva",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "YouTube / Google",
    "territory": "Vida activa y rendimiento",
    "interest": "Running para principiantes",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "YouTube / Google",
    "territory": "Vida activa y rendimiento",
    "interest": "Suplementos deportivos",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "YouTube / Google",
    "territory": "Vida activa y rendimiento",
    "interest": "Comparativas de bebidas hidratantes",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "YouTube / Google",
    "territory": "Vida activa y rendimiento",
    "interest": "Productividad diaria",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "YouTube / Google",
    "territory": "Vida activa y rendimiento",
    "interest": "Bebidas sin azúcar",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Carlos",
    "platform": "YouTube / Google",
    "territory": "Vida activa y rendimiento",
    "interest": "Ciclismo",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Día / recuperación",
    "tactic": "Reach video + contexto de contenido",
    "validation": "No asumir que todas las keywords son segmentos seleccionables"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Bienestar",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Nutrición",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Alimentación saludable",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Vida saludable",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Meditación",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Ejercicio físico",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Caminatas",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Familia",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Cuidado personal",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Vitaminas",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Yoga",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Facebook",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Compras online",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Instagram",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Bienestar",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Instagram",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Mindfulness",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Instagram",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Nutrición",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Instagram",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Autocuidado",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Instagram",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Meditación",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Instagram",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Yoga",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Instagram",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Hábitos saludables",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Instagram",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Cuidado personal",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "Meta / Instagram",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Rutinas de noche",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "TikTok",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Lifestyle",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "TikTok",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Bienestar",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "TikTok",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Contenido educativo",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "TikTok",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Rutinas nocturnas",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "TikTok",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Mindfulness",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "TikTok",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Nutrición",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "TikTok",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Hábitos saludables",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "TikTok",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Cuidado personal",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "TikTok",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Contenido de expertos",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Higiene del sueño",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Rutinas para dormir",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Cómo organizar horarios de sueño",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Hábitos nocturnos",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Cafeína y sueño",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Meditación guiada",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Alimentación saludable",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Suplementos y vitaminas",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Ritmo circadiano",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Bienestar familiar",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Rutina de descanso",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  },
  {
    "cluster": "Julián",
    "platform": "YouTube / Google",
    "territory": "Hábitos y bienestar consciente",
    "interest": "Cuidado diario",
    "type": "Interés si existe / búsqueda o contexto",
    "priority": "Alta",
    "product": "Noche / Día",
    "tactic": "Reach educativo + video experto",
    "validation": "No segmentar por diagnósticos ni inferir condiciones médicas"
  }
];
